version: '3.9'
services:
  apache1:
    image: httpd:latest
    volumes:
    - ./FRONTEND:/usr/local/apache2/htdocs
    ports:
    - "8081:80"

  nginx:
    image: nginx:latest
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "81:80"

  APIWeb:
    image: docker.io/bitnami/laravel:10
    volumes:
    - ./APIWeb/:/app
    environment:
    - DB_HOST=mysql
    - DB_PORT=3306
    - DB_USERNAME=Benat
    - DB_PASSWORD=12345678
    - DB_DATABASE=Benat
    ports:
    - "8085:8000"
    depends_on:
            mysql:
                condition: service_healthy

    command: ["sh", "-c", "php artisan migrate:refresh --seed && php artisan passport:install --force && php artisan serve --host=0.0.0.0"]

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'Benat'
      MYSQL_USER: 'Benat'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './BBDD/:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
  phpmyadmin:
        image: 'phpmyadmin:latest'
        ports:
            - 8084:80
        environment:
            - PMA_ARBITRARY=1