version: '3.3'
services:
  apache:
    image: httpd:latest
    volumes:
      - ./datos/web/:/usr/local/apache2/htdocs/
    ports:
      - "8081:80"
  nginx:
    image: nginx:latest
    volumes:
      - ./datos/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"

  laravel:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8083:8000'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=mysql
      - DB_PASSWORD=mysql
      - DB_DATABASE=mysql
    volumes:
      - './datos/laravel:/app'
    # command: ["sh", "-c", "php artisan migrate && php artisan passport:install --force && php artisan serve --host=0.0.0.0"]
    # depends_on:
    #          mysql:
    #             condition: service_healthy
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'mysql'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - './datos/mysql/:/var/lib/mysql'
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #   interval: 10s
    #   retries: 5
    #   start_period: 10s
    #   timeout: 5s  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8084:80"
    environment:
      - PMA_ARBITRARY=1
